/**
 * DGP 数据常量。
 * 1:1 Ported from legacy lib/dgp/2_data.js 的所有字段、文案、数值。
 * 只做 JS → TS 语法/类型调整，不修改任何游戏数值与文案。
 */

import type {
  BuckleMap,
  IdCore,
  JyamatoTemplate,
  Supporter,
  SecretMission,
  StageDef,
} from './types';

export const BUCKLES: BuckleMap = {
  Entry: {
    id: 'Entry',
    name: '素体',
    tier: 'base',
    hp: 0,
    atk: 0,
    tags: ['basic'],
    pref: {},
    skills: [
      { name: '素体拳击', type: 'attack', cd: 0, dmg: 0.8 },
      {
        name: '基础回旋踢',
        type: 'tactical',
        cd: 2,
        dmg: 1.0,
        effect: { type: 'Stun', duration: 1, chance: 0.1 },
      },
    ],
  },
  // --- 双重指挥（阶段一） ---
  Command_Raising: {
    id: 'Command_Raising',
    name: '喷射器',
    formName: '跃升',
    tier: 'large',
    hp: 3000,
    atk: 90,
    tags: ['melee', 'command_raising'],
    pref: {},
    weapon: { name: '跃升斩剑', type: 'sword' },
    skills: [
      { name: '跃升斩剑·基础斩击', type: 'attack', cd: 0, dmg: 1.0, hits: 1 },
      {
        name: 'Raising Strike (跃升重劈)',
        type: 'tactical',
        cd: 2,
        dmg: 1.8,
        hits: 3,
        shield: true, // 附带 20% 减伤护盾苟活
        hpScale: 0.20,
      },
    ],
  },
  // --- 双重指挥（阶段二） ---
  Command_Twin: {
    id: 'Command_Twin',
    name: '双重指挥',
    tier: 'mythic',
    hp: 9999,
    atk: 600,
    tags: ['twin_command', 'god'],
    pref: {},
    skills: [
      // Jet 模式技能
      { name: 'Jet 高速连续剑', type: 'attack', mode: 'Jet', cd: 0, dmg: 1.2, hits: 3 },
      { name: 'Jet 战术突击', type: 'tactical', mode: 'Jet', cd: 2, dmg: 3.5, hits: 5, selfBuff: { type: 'Dodge Up', duration: 1 } },
      { name: 'Tactical Raising (战术跃升突刺)', type: 'ultimate', mode: 'Jet', cd: 4, dmg: 4.2, hits: 4 },
      { name: 'Jet Twin Victory (喷气机·双重胜利)', type: 'ultimate', mode: 'Jet', cd: 5, dmg: 4.8, trueDmg: true, alwaysHit: true },
      // Cannon 模式技能
      { name: 'Cannon 破坏重炮', type: 'attack', mode: 'Cannon', cd: 0, dmg: 1.5, hits: 1 },
      { name: 'Cannon 轨道轰炸', type: 'tactical', mode: 'Cannon', cd: 2, dmg: 3.8, aoe: true, ignoreDef: 0.5 },
      { name: 'Cannon Twin Victory (加农炮·双重胜利)', type: 'ultimate', mode: 'Cannon', cd: 5, dmg: 5.5, alwaysCrit: true, ignoreShield: true },
    ],
  },
  Magnum: {
    id: 'Magnum',
    name: '马格南',
    tier: 'large',
    hp: 3500,
    atk: 100,
    tags: ['ranged', 'high_dmg', 'gunner'],
    pref: { int: 2.0, agi: 0.5 },
    weapon: { name: '马格南射击者40X', type: 'firearm' },
    skills: [
      { name: '40X手枪·极速连射', type: 'attack', cd: 0, dmg: 1.0, hits: 2 },
      {
        name: 'Bullet Charge (充能扫射)',
        type: 'tactical',
        cd: 2,
        dmg: 1.5,
        hits: 3,
        randomTargets: true,
      },
      {
        name: '40X步枪·精准瞄准',
        type: 'tactical',
        cd: 3,
        dmg: 1.8,
        target: 'lowest_hp',
        ignoreFront: true,
        effect: { type: 'Locked-on', duration: 2, chance: 1.0 },
      },
      {
        name: 'Magnum Strike (马格南骑士踢)',
        type: 'ultimate',
        cd: 4,
        dmg: 2.8,
        cond: 'Locked-on',
        condMult: 1.5,
      },
      {
        name: 'Magnum Tactical Blast (战术爆破)',
        type: 'ultimate',
        cd: 5,
        dmg: 2.8,
        aoe: true,
        alwaysCrit: true,
        isWeaponSlotSkill: true,
      },
    ],
  },
  Zombie: {
    id: 'Zombie',
    name: '僵尸',
    tier: 'large',
    hp: 3500,
    atk: 100,
    tags: ['melee', 'lifesteal', 'tank', 'poison'],
    pref: { str: 2.5 },
    weapon: { name: '僵尸破坏者', type: 'chainsaw_sword' },
    skills: [
      {
        name: '破坏者·狂野锯斩',
        type: 'attack',
        cd: 0,
        dmg: 1.0,
        lifesteal: 0.35,
        hits: 2,
      },
      {
        name: '蓄毒之臂·狂野利爪',
        type: 'tactical',
        cd: 2,
        dmg: 1.5,
        aoe: true,
        effect: { type: 'Poison', duration: 2, chance: 1.0 },
        lifesteal: 0.4,
      },
      {
        name: 'Zombie Strike (僵尸突击)',
        type: 'ultimate',
        cd: 4,
        dmg: 2.8,
        trueDmg: true,
        lifesteal: 0.5,
        effect: { type: 'Vulnerable', duration: 2, chance: 0.8 },
      },
      {
        name: 'Tactical Break (战术撕裂)',
        type: 'ultimate',
        cd: 5,
        dmg: 2.8,
        aoe: true,
        isWeaponSlotSkill: true,
      },
    ],
  },
  Beat: {
    id: 'Beat',
    name: '节拍',
    tier: 'large',
    hp: 3500,
    atk: 100,
    tags: ['melee', 'magic', 'support', 'aoe', 'heal'],
    pref: { int: 2.8 },
    weapon: { name: '节拍战斧', type: 'guitar_axe' },
    skills: [
      {
        name: '战斧·摇滚扫弦',
        type: 'attack',
        cd: 0,
        dmg: 1.0,
        hits: 2,
        magic: true,
      },
      {
        name: '治愈狂想曲',
        type: 'tactical',
        cd: 3,
        dmg: 0,
        selfHeal: true,
        healIntMult: 8,
        selfBuff: { type: 'Atk Up', duration: 2 },
      },
      {
        name: '动感音波',
        type: 'tactical',
        cd: 3,
        dmg: 1.5,
        magic: true,
        aoe: false,
        maxTargets: 6,
        effect: { type: 'Stun', duration: 1, chance: 0.4 },
      },
      {
        name: 'Beat Strike (节拍突击)',
        type: 'ultimate',
        cd: 4,
        dmg: 2.5,
        magic: true,
        hits: 3,
      },
      {
        name: '战术合奏',
        type: 'ultimate',
        cd: 5,
        dmg: 2.8,
        magic: true,
        aoe: true,
        isWeaponSlotSkill: true,
      },
    ],
  },
  Ninja: {
    id: 'Ninja',
    name: '忍者',
    tier: 'large',
    hp: 3500,
    atk: 100,
    tags: ['melee', 'dodge', 'assassin', 'wind'],
    pref: { agi: 2.5 },
    weapon: { name: '忍者双重刃', type: 'twin_blade' },
    skills: [
      {
        name: '双重刃·流风连斩',
        type: 'attack',
        cd: 0,
        dmg: 1.0,
        hits: 2,
        cond: 'hasClone',
        condMult: 1.5,
      },
      {
        name: 'Tactical Slash (战术斩击)',
        type: 'tactical',
        cd: 2,
        dmg: 1.5,
        hits: 1,
        aoe: true,
        cond: 'hasClone',
        condMult: 1.5,
      },
      {
        name: '忍法·风遁分身',
        type: 'tactical',
        cd: 4,
        dmg: 0,
        summon: {
          id: 'NinjaClone',
          name: '风遁分身',
          inheritStats: 0.3,
          duration: 3,
        },
      },
      {
        name: 'Ninja Strike (忍者突击)',
        type: 'ultimate',
        cd: 4,
        dmg: 2.8,
        cond: 'hasClone',
        condMult: 1.5,
      },
      {
        name: 'Tactical Finish (战术终结)',
        type: 'ultimate',
        cd: 5,
        dmg: 2.8,
        ignoreShield: true,
        isWeaponSlotSkill: true,
        cond: 'hasClone',
        condMult: 1.5,
      },
    ],
  },
  Monster: {
    id: 'Monster',
    name: '怪兽',
    tier: 'large',
    hp: 3500,
    atk: 100,
    tags: ['melee', 'burst', 'stun', 'tank'],
    pref: { str: 3.0 },
    weapon: { name: '怪兽重拳', type: 'gauntlet' },
    skills: [
      { name: '怪兽重拳·星芒直击', type: 'attack', cd: 0, dmg: 1.2, hits: 1 },
      {
        name: '能量延展·陨石突袭',
        type: 'tactical',
        cd: 2,
        dmg: 1.8,
        ignoreDef: 0.3,
        effect: { type: 'Stun', duration: 1, chance: 0.5 },
      },
      {
        name: '狂野本能·怪兽觉醒',
        type: 'tactical',
        cd: 4,
        dmg: 0,
        selfBuff: { type: 'Burst', duration: 1 },
        selfHeal: false,
        shield: true,
        hpScale: 0.15,
      },
      {
        name: 'Monster Strike (怪兽突击)',
        type: 'ultimate',
        cd: 4,
        dmg: 2.8,
        trueDmg: true,
        effect: { type: 'Stun', duration: 1, chance: 1.0 },
      },
      {
        name: '战术粉碎',
        type: 'ultimate',
        cd: 5,
        dmg: 2.8,
        ignoreShield: true,
        isWeaponSlotSkill: true,
      },
    ],
  },
  Boost: {
    id: 'Boost',
    name: '推进器',
    tier: 'large',
    hp: 2400,
    atk: 200,
    tags: ['melee', 'consumable', 'burst', 'fire', 'vehicle'],
    pref: { str: 1.0, agi: 2.0 },
    weapon: { name: '推进者摩托', type: 'vehicle' },
    skills: [
      {
        name: '排气轰击',
        type: 'attack',
        cd: 0,
        dmg: 1.2,
        hits: 1,
        effect: { type: 'Burn', duration: 2, chance: 0.5 },
      },
      {
        name: 'Boost Time！',
        type: 'tactical',
        cd: 3,
        dmg: 0,
        selfBuff: { type: 'Burst', duration: 2 },
        selfHeal: false,
        shield: true,
        hpScale: 0.15,
      },
      {
        name: '推进者·狂兽突击',
        type: 'tactical',
        cd: 4,
        dmg: 2.0,
        aoe: true,
        ignoreDef: 0.5,
        effect: { type: 'Burn', duration: 3, chance: 1.0 },
      },
      {
        name: 'Boost Strike',
        type: 'ultimate',
        cd: 4,
        dmg: 3.2,
        trueDmg: true,
        ignoreShield: true,
        removeBoost: true,
      },
    ],
  },
  Arrow: {
    id: 'Arrow',
    name: '弓箭',
    tier: 'small',
    hp: 1000,
    atk: 30,
    tags: ['ranged', 'small'],
    pref: { agi: 1.5 },
    skills: [
      {
        name: '武装散射',
        type: 'tactical',
        cd: 2,
        dmg: 1.2,
        hits: 2,
        randomTargets: true,
      },
    ],
  },
  Water: {
    id: 'Water',
    name: '水管',
    tier: 'small',
    hp: 1000,
    atk: 30,
    tags: ['magic', 'small'],
    pref: { int: 1.5 },
    skills: [
      {
        name: '高压水柱',
        type: 'tactical',
        cd: 3,
        dmg: 1.2,
        effect: { type: 'Wet', duration: 2, chance: 1.0 },
      },
    ],
  },
  Propeller: {
    id: 'Propeller',
    name: '螺旋桨',
    tier: 'small',
    hp: 1000,
    atk: 30,
    tags: ['melee', 'small'],
    pref: { agi: 1.0, str: 0.5 },
    skills: [
      {
        name: '滞空斩击',
        type: 'tactical',
        cd: 2,
        dmg: 1.2,
        selfBuff: { type: 'Dodge Up', duration: 1 },
      },
    ],
  },
  Hammer: {
    id: 'Hammer',
    name: '战锤',
    tier: 'small',
    hp: 1000,
    atk: 30,
    tags: ['melee', 'small'],
    pref: { str: 2.0 },
    skills: [
      {
        name: '撼地一击',
        type: 'tactical',
        cd: 3,
        dmg: 1.2,
        effect: { type: 'Vulnerable', duration: 2, chance: 1.0 },
      },
    ],
  },
  Shield: {
    id: 'Shield',
    name: '盾牌',
    tier: 'small',
    hp: 1000,
    atk: 30,
    tags: ['defense', 'small', 'tank'],
    pref: { str: 1.0, int: 1.0 },
    skills: [
      {
        name: '绝对防御',
        type: 'tactical',
        cd: 3,
        dmg: 0,
        selfBuff: { type: 'Shield', hpScale: 0.15 },
      },
    ],
  },
  Fever: {
    id: 'Fever',
    name: '狂热插槽',
    tier: 'legendary',
    hp: 800,
    atk: 40,
    tags: ['fever'],
    pref: {},
    skills: [
      {
        name: '黄金狂热爆裂',
        type: 'ultimate',
        cd: 6,
        dmg: 3.8,
        trueDmg: true,
        dispelBuffs: true,
      },
    ],
  },
};

export const ID_CORES: IdCore[] = [
  {
    id: 'Fox',
    icon: '🦊',
    name: '狐狸',
    affinity: 'Magnum',
    passive: 'crit',
    passiveName: '要害暴击',
    desc: '暴击率 20%，额外伤害提升',
  },
  {
    id: 'Bull',
    icon: '🐃',
    name: '水牛',
    affinity: 'Zombie',
    passive: 'undead',
    passiveName: '狂战不屈',
    desc: '受致命伤时25%锁血不死',
  },
  {
    id: 'Tanuki',
    icon: '🦝',
    name: '狸猫',
    affinity: 'Ninja',
    passive: 'luck',
    passiveName: '欧皇强运',
    desc: '大带扣获取率翻倍',
  },
  {
    id: 'Cat',
    icon: '🐱',
    name: '猫咪',
    affinity: 'Beat',
    passive: 'agile',
    passiveName: '灵动身姿',
    desc: '额外 15% 基础闪避',
  },
  {
    id: 'Pumpkin',
    icon: '🎃',
    name: '棕熊',
    affinity: 'Monster',
    passive: 'thorns',
    passiveName: '荆棘反伤',
    desc: '受击反弹20%真实伤害',
  },
  {
    id: 'Wolf',
    icon: '🐺',
    name: '野狼',
    affinity: 'Zombie',
    passive: 'blood',
    passiveName: '嗜血本能',
    desc: 'HP低于50%增伤40%',
  },
  {
    id: 'Penguin',
    icon: '🐧',
    name: '企鹅',
    affinity: 'Ninja',
    passive: 'survive',
    passiveName: '抗压体质',
    desc: '所有受伤降低15%',
  },
  {
    id: 'Eagle',
    icon: '🦅',
    name: '飞鹰',
    affinity: 'Magnum',
    passive: 'precise',
    passiveName: '鹰眼锁定',
    desc: '无视目标基础闪避',
  },
];

export const JYAMATOS: Record<string, JyamatoTemplate> = {
  Pawn: {
    id: 'Pawn',
    name: '邪魔徒步兵',
    hp: 1600,
    atk: 35,
    icon: '🧟',
    tier: 'normal',
    str: 30,
    agi: 20,
    int: 10,
    skills: [{ name: '邪魔徒利爪', type: 'attack', cd: 0, dmg: 1.0 }],
  },
  Rook: {
    id: 'Rook',
    name: '战车邪魔徒',
    hp: 4000,
    atk: 70,
    icon: '♟️',
    tier: 'elite',
    str: 80,
    agi: 10,
    int: 20,
    skills: [
      {
        name: '重装冲撞',
        type: 'tactical',
        cd: 2,
        dmg: 1.5,
        effect: { type: 'Stun', duration: 1, chance: 0.2 },
      },
    ],
  },
  Rider: {
    id: 'Rider',
    name: '邪魔徒骑士',
    hp: 8000,
    atk: 120,
    icon: '💀',
    tier: 'boss',
    str: 90,
    agi: 60,
    int: 50,
    skills: [
      { name: '狂暴扫射', type: 'attack', cd: 0, dmg: 1.0, aoe: true },
      {
        name: '猛毒骑士踢',
        type: 'ultimate',
        cd: 3,
        dmg: 2.5,
        effect: { type: 'Poison', duration: 2, chance: 1.0 },
      },
    ],
  },
};

export const SUPPORTERS: Supporter[] = [
  { id: 'Ziin', name: '吉恩', targetBuckle: 'Magnum', icon: '🦊' },
  { id: 'Kekera', name: '凯凯拉', targetBuckle: 'Ninja', icon: '🐸' },
  { id: 'Kyuun', name: '秋恩', targetBuckle: 'Beat', icon: '🦁' },
  { id: 'Beroba', name: '贝洛芭', targetBuckle: 'Zombie', icon: '🌹' },
];

export const SECRET_MISSIONS: SecretMission[] = [
  {
    id: 'survival',
    name: '绝境求生',
    desc: '在生命值极不健康的情况下依然屹立不倒',
    condition: (player) => player.hp / player.maxHp <= 0.35,
  },
  {
    id: 'unarmed',
    name: '素体的觉悟',
    desc: '在没有任何带扣武装的情况下迎战强敌',
    condition: (player) => player.buckles.length === 0,
  },
  {
    id: 'pacifist',
    name: '和平的守护者',
    desc: '坚持不淘汰他人，保持着纯粹的善意',
    condition: (player) => player.kills === 0,
  },
  {
    id: 'scars',
    name: '伤痕的勋章',
    desc: '承受了海量的伤害却坚韧不拔',
    condition: (player) => player.maxHp - player.hp > 600,
  },
  {
    id: 'agile',
    name: '风之轨迹',
    desc: '展现出了超越常人的灵动身姿',
    condition: (player) => player.agi > 60,
  },
  {
    id: 'strength',
    name: '绝对力量',
    desc: '凭借纯粹的蛮力震撼了赛场',
    condition: (player) => player.str > 60,
  },
  {
    id: 'intelligence',
    name: '战术天才',
    desc: '以过人的智慧洞悉了战场的局势',
    condition: (player) => player.int > 60,
  },
  {
    id: 'lucky',
    name: '茨姆莉的捉迷藏',
    desc: '在战场的角落意外发现了游戏向导留下的补给',
    condition: () => true,
  },
];

export const STAGE_POOL: StageDef[] = [
  {
    id: 'Ceasefire',
    name: '停战休整区',
    type: 'safe',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【停战休整区】！”\n🕊️【场地效果】如果有邪魔徒在场，斗争被严令禁止！所有骑士间的互相伤害强行归零，大家趁机开始恢复体力！`,
  },
  {
    id: 'Defense',
    name: '绝对防御阵地',
    type: 'safe',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【绝对防御阵地】！”\n🛡️【场地效果】空气变得异常粘稠！所有单位受到的伤害减半，护盾效果翻倍！`,
  },
  {
    id: 'Zero',
    name: '极度深寒',
    type: 'safe',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【极度深寒】阶段！”\n❄️【场地效果】极寒降临！所有技能冷却被冻结，推进器无法点火，只能使用基础攻击进行肉搏！`,
  },
  {
    id: 'Asura',
    name: '修罗竞技场',
    type: 'danger',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【修罗竞技场】阶段！”\n⚔️【场地效果】DGP保护协议被强行关闭！所有护盾碎裂！这是毫无顾忌的杀戮时刻！`,
  },
  {
    id: 'Toxic',
    name: '毒气沼泽',
    type: 'danger',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【毒气沼泽】阶段！”\n☠️【场地效果】致命毒气弥漫！回合结束时所有人将受到真实伤害，处于湿身或中毒状态者伤害翻倍！`,
  },
  {
    id: 'Midnight',
    name: '暗夜捉迷藏',
    type: 'danger',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【暗夜捉迷藏】阶段！”\n🌑【场地效果】视野被黑暗剥夺！所有人的闪避率极大幅度提升，但一旦受伤必定承受致命暴击！`,
  },
  {
    id: 'Carnival',
    name: '邪魔徒狂欢节',
    type: 'chaos',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【邪魔徒狂欢节】阶段！”\n🧟【场地效果】邪魔徒陷入了集体狂暴！它们获得了攻击提升与高额吸血，并且源源不断地涌入战场！`,
  },
  {
    id: 'Labyrinth',
    name: '失重迷宫',
    type: 'chaos',
    startLog: `🌐【区域切换】游戏向导 茨姆莉 宣布：“大奖赛突发特殊规则！本轮游戏进入【失重迷宫】阶段！”\n🌀【场地效果】重力与方向感完全丧失！单体攻击目标将变得完全随机，力量失去作用，唯有敏捷才能保命！`,
  },
];

export const BUFF_DICT: Record<string, string> = {
  Poison: '中毒',
  Burn: '灼烧',
  Stun: '眩晕',
  Vulnerable: '破甲',
  'Locked-on': '锁定',
  Wet: '湿身',
  Shield: '护盾',
  Phantom: '幻影',
  'Atk Up': '攻击提升',
  Regen: '持续治愈',
  Burst: '极限爆发',
  'Dodge Up': '灵动',
};

export const BUFF_ICONS: Record<string, string> = {
  Poison: '☠️中毒',
  Burn: '🔥灼烧',
  Stun: '💫眩晕',
  Vulnerable: '💔破甲',
  'Locked-on': '🎯锁定',
  Wet: '💧湿身',
  Shield: '🛡️护盾',
  Phantom: '🌫️幻影',
  'Atk Up': '🔥激昂',
  Regen: '💚治愈',
  Burst: '🚀爆发',
  'Dodge Up': '🍃灵动',
};
