import { COLORS, SKILL_TAGS, STATUS_EFFECTS } from './data/constants';
import { CHEESY_LINES_POOL, COLD_JOKES_POOL, HELL_JOKES_POOL, TOKUSATSU_BASIC_POOL } from './data/textPools';
import { EXODIA_CARD, GACHA_NORMAL_POOL, GACHA_SSR_POOL, RED_FURY_POOL, SUICIDE_POOL } from './data/gachaPools';
import { BABY_SUPPORT_POOL, DIVA_BUFF_POOL, VALORANT_GUNS_POOL, VALORANT_POOL } from './data/supportPools';
import { TUJUANJUAN_CALC_POOL, TUJUANJUAN_STYLE_POOL } from './data/rabbitPools';
import { CHIMERA_PLUGIN_POOL, SUCCUBUS_COUNTER_POOL } from './data/evolutionPools';

export { COLORS, SKILL_TAGS, STATUS_EFFECTS } from './data/constants';
export { CHEESY_LINES_POOL, COLD_JOKES_POOL, HELL_JOKES_POOL, TOKUSATSU_BASIC_POOL } from './data/textPools';
export { EXODIA_CARD, GACHA_NORMAL_POOL, GACHA_SSR_POOL, RED_FURY_POOL, SUICIDE_POOL } from './data/gachaPools';
export { BABY_SUPPORT_POOL, DIVA_BUFF_POOL, VALORANT_GUNS_POOL, VALORANT_POOL } from './data/supportPools';
export { TUJUANJUAN_CALC_POOL, TUJUANJUAN_STYLE_POOL } from './data/rabbitPools';
export { CHIMERA_PLUGIN_POOL, SUCCUBUS_COUNTER_POOL } from './data/evolutionPools';

export const namerenaData = {
  SKILL_TAGS, STATUS_EFFECTS, COLORS,
  COLD_JOKES_POOL, HELL_JOKES_POOL, CHEESY_LINES_POOL, TOKUSATSU_BASIC_POOL,
  RED_FURY_POOL, SUICIDE_POOL, GACHA_NORMAL_POOL, EXODIA_CARD, GACHA_SSR_POOL,
  DIVA_BUFF_POOL, VALORANT_POOL, VALORANT_GUNS_POOL, BABY_SUPPORT_POOL,
  TUJUANJUAN_CALC_POOL, TUJUANJUAN_STYLE_POOL,
  SUCCUBUS_COUNTER_POOL, CHIMERA_PLUGIN_POOL,
};
