export type YuzuSurtrRuleEvidence = {
  id: string;
  subject: 'yuzu_prophet' | 'surtr' | 'cross_system';
  rule: string;
  deterministicCase: string;
  eventAssertions: string[];
  logAssertions: string[];
};

export const YUZU_SURTR_RULE_CATALOG: readonly YuzuSurtrRuleEvidence[] = [
  {
    id: 'YP-01',
    subject: 'yuzu_prophet',
    rule: '预言家只在存在存活柚子时进行一次登场判定。',
    deterministicCase: 'Prophet spawn check is one-shot and requires an active Yuzu',
    eventAssertions: ['失败判定后不得创建预言家单位'],
    logAssertions: ['失败原因只记录一次'],
  },
  {
    id: 'YP-02',
    subject: 'yuzu_prophet',
    rule: '预言家绑定唯一柚子；无可接管对象时只生成一名保底史尔特尔。',
    deterministicCase: 'Prophet spawn fixes stats, mark, NPC state, and fallback Surtr exactly once',
    eventAssertions: ['绑定 ID、NPC 能力、阶段属性和保底召唤唯一'],
    logAssertions: ['登场、绑定和保底召唤均有明确日志'],
  },
  {
    id: 'YP-03',
    subject: 'yuzu_prophet',
    rule: '五类被接管召唤物保留自身技能、索敌和伤害归属，绝不进入拼点。',
    deterministicCase: 'All five controlled summon kinds retain their own skills, targets, and damage attribution',
    eventAssertions: ['史尔特尔、诗怀雅、琳琅诗怀雅、幽灵鲨、归溟幽灵鲨均以自身 ID 产生行动与伤害'],
    logAssertions: ['五类行动分支均不得出现预言家拼点日志'],
  },
  {
    id: 'YP-04',
    subject: 'yuzu_prophet',
    rule: '预言家登场后新生成的四类鸮召唤物必须立即接管。',
    deterministicCase: 'New Owl summons are captured immediately and cannot be used as Surtr tributes',
    eventAssertions: ['每个新召唤物在生成回调内改变所有权且不能作为祭品'],
    logAssertions: ['四名召唤物分别记录接管来源'],
  },
  {
    id: 'YP-05',
    subject: 'yuzu_prophet',
    rule: '绑定柚子存活时，预言家拒绝其他来源的伤害、状态、驱散和处决。',
    deterministicCase: 'Source immunity rejects non-bound damage, status, dispel, and defeat while accepting bound Yuzu effects',
    eventAssertions: ['非法来源不改变生命、状态或死亡标志'],
    logAssertions: ['每个拒绝分支说明绑定来源免疫'],
  },
  {
    id: 'YP-06',
    subject: 'yuzu_prophet',
    rule: '预言家不会感染矿石病，合法环境致死仍可触发共同退场。',
    deterministicCase: 'Prophet permanently rejects Originium infection while legal environmental retreat preserves its cause',
    eventAssertions: ['矿石病实例始终为零；环境致死只触发一次退场'],
    logAssertions: ['源石同源与真实退场原因均可读'],
  },
  {
    id: 'YP-07',
    subject: 'yuzu_prophet',
    rule: '预言家与绑定柚子互相优先，但仍遵守强制目标、傀儡挡刀和魅惑合法性。',
    deterministicCase: 'Prophet priority ignores taunt but still obeys forced targets, puppet interception, and charm legality',
    eventAssertions: ['最终受击目标与目标替换规则一致'],
    logAssertions: ['挡刀或控制不得被写成直接命中原目标'],
  },
  {
    id: 'YP-08',
    subject: 'yuzu_prophet',
    rule: '被接管召唤物真实死亡只结算一次击杀，再转化一枚结晶。',
    deterministicCase: 'Controlled summon real death settles kill and death context before exactly one dedicated crystal conversion',
    eventAssertions: ['一次 defeat、一次击杀归属、一次结晶生成'],
    logAssertions: ['击败日志必须先于死亡转化日志'],
  },
  {
    id: 'YP-09',
    subject: 'yuzu_prophet',
    rule: '进入二阶段时抹杀全部接管召唤物，不触发普通死亡收益，也不再返还。',
    deterministicCase: 'Phase transition erases summons cleanly and its retreat log never claims phase-one control return',
    eventAssertions: ['抹杀不产生普通 defeat 奖励或复活'],
    logAssertions: ['二阶段与共同退场文案不得声称返还已抹杀召唤物'],
  },
  {
    id: 'YP-10',
    subject: 'yuzu_prophet',
    rule: '源石开满大地在拼点前消耗结晶，拼点失败也不返还。',
    deterministicCase: 'Originium Land pays its crystal before clash and never refunds it on loss',
    eventAssertions: ['结晶消耗发生于 clash 根事件之前且只发生一次'],
    logAssertions: ['前置代价、拼点和失败结果顺序完整'],
  },
  {
    id: 'YP-11',
    subject: 'yuzu_prophet',
    rule: '理解普瑞赛斯在拼点前提供护盾，拼点失败也保留。',
    deterministicCase: 'Understand Puruisaishi grants its 300 barrier before clash and keeps it on loss',
    eventAssertions: ['护盾增加量精确且发生于拼点前'],
    logAssertions: ['护盾前置效果和拼点结果分别记录'],
  },
  {
    id: 'YP-12',
    subject: 'yuzu_prophet',
    rule: '二阶段防御拼点胜利取消整条受击分支，失败则在常规减伤后乘算减半。',
    deterministicCase: 'Phase-two defense cancels an entire branch on win and applies post-mitigation 50% damage on loss',
    eventAssertions: ['胜利分支无伤害；失败分支伤害顺序和数值精确'],
    logAssertions: ['整枝闪避与失败减伤不得同时出现'],
  },
  {
    id: 'YP-13',
    subject: 'yuzu_prophet',
    rule: '二阶段伤害公式固定，AOE 附加状态只跟随实际命中分支。',
    deterministicCase: 'Prophet damage formulas are exact and AOE statuses only follow a connected branch',
    eventAssertions: ['伤害与状态目标逐分支对应'],
    logAssertions: ['未命中或取消分支明确说明未施加状态'],
  },
  {
    id: 'YP-14',
    subject: 'yuzu_prophet',
    rule: '必须执行源石计划只处决预判确实致死的目标，并按随机顺序逐一正式结算。',
    deterministicCase: 'Execution preview names a genuinely lethal target and formal resolution logs its randomized order',
    eventAssertions: ['预判结果和正式 defeat 目标一致'],
    logAssertions: ['随机顺序、跳过与正式处决均有因果上下文'],
  },
  {
    id: 'YP-15',
    subject: 'yuzu_prophet',
    rule: '一阶段共同退场返还存活召唤物、清除矿石病和标记，且不奖励击杀。',
    deterministicCase: 'Common retreat returns survivors, clears infection and marks, awards no kills, and plays its quote once',
    eventAssertions: ['返还、清理、零击杀和一次性退场状态一致'],
    logAssertions: ['启动、清理、长台词和完成按顺序各一次'],
  },
  {
    id: 'YP-16',
    subject: 'yuzu_prophet',
    rule: '保底史尔特尔随事件退场，黄昏余命不会留下后续行动。',
    deterministicCase: 'Fallback Surtr retreat clears afterglow before zeroing HP',
    eventAssertions: ['余命状态先清理，再将单位设为不可行动退场'],
    logAssertions: ['共同退场后不得再出现保底史尔特尔行动'],
  },
  {
    id: 'YP-17',
    subject: 'yuzu_prophet',
    rule: '真实史尔特尔返还时恢复两名共同主人和原阵营关系。',
    deterministicCase: 'Prophet retreat restores and names both Surtr owners without leaking internal IDs',
    eventAssertions: ['ownershipSuspended 解除且两名主人 ID 恢复'],
    logAssertions: ['返还日志写出两名主人，不泄漏 UUID'],
  },
  {
    id: 'YP-18',
    subject: 'yuzu_prophet',
    rule: '共同退场清除事件单位的延迟伤害与后续幽灵日志。',
    deterministicCase: 'Puruisaishi shield depletion precedes retreat and retired event units leave no deferred logs',
    eventAssertions: ['事件单位退场后没有待处理伤害事件'],
    logAssertions: ['护盾耗尽先于共同退场，完成后不再引用退场单位'],
  },
  {
    id: 'ST-01',
    subject: 'surtr',
    rule: '史尔特尔是高级召唤物，基础属性与青眼白龙基准一致。',
    deterministicCase: 'Surtr is an advanced summon with exact Blue-Eyes baseline stats',
    eventAssertions: ['召唤分类与基础面板精确'],
    logAssertions: ['普通召唤池不得出现史尔特尔'],
  },
  {
    id: 'ST-02',
    subject: 'surtr',
    rule: '只有同一名鸮的基础诗怀雅与基础幽灵鲨可作为祭品，并确立牢鳄、鸮双主人。',
    deterministicCase: 'Surtr tribute order, Heaven hooks, joint owners, and conflict targeting are exact',
    eventAssertions: ['两次祭品死亡、一次召唤和双主人关系顺序固定'],
    logAssertions: ['祭品、召唤和共同主人日志完整'],
  },
  {
    id: 'ST-03',
    subject: 'surtr',
    rule: '跨鸮、异格替代品和被接管材料均不能完成史尔特尔召唤。',
    deterministicCase: 'Surtr rejects cross-Owl and substitute tribute combinations',
    eventAssertions: ['非法组合不生成史尔特尔'],
    logAssertions: ['失败原因指出缺少同源基础祭品'],
  },
  {
    id: 'ST-04',
    subject: 'surtr',
    rule: '史尔特尔的伤害、攻击转法术、穿透和黄昏成长公式精确。',
    deterministicCase: 'Surtr formulas, ATK-to-magic conversion, penetration, and uncapped scaling are exact',
    eventAssertions: ['固定随机序列下每项伤害数值一致'],
    logAssertions: ['预估与实际结算不得重复或矛盾'],
  },
  {
    id: 'ST-05',
    subject: 'surtr',
    rule: '每只史尔特尔一局只能发动一次黄昏，抵挡不会返还。',
    deterministicCase: 'Twilight setup is once-only and target spell blocks never refund it',
    eventAssertions: ['twilightUsed 一次置位且不回滚'],
    logAssertions: ['唯一一次消耗与每个抵挡目标分别可读'],
  },
  {
    id: 'ST-06',
    subject: 'surtr',
    rule: '逐目标反击只中断对应的黄昏命中，不取消其他目标或返还黄昏。',
    deterministicCase: 'Per-target counters interrupt one Twilight impact without misleading logs or refunds',
    eventAssertions: ['未被反击的目标仍独立结算'],
    logAssertions: ['中断、其他命中与黄昏消耗前后一致'],
  },
  {
    id: 'ST-07',
    subject: 'surtr',
    rule: '多目标技能在施放开始时锁定目标，途中阵营变化不改写剩余目标。',
    deterministicCase: 'Surtr multi-target skills preserve every cast-start target through mid-cast affiliation changes',
    eventAssertions: ['action_start 目标集合与各伤害分支一致'],
    logAssertions: ['目标列表与逐目标结算不矛盾'],
  },
  {
    id: 'ST-08',
    subject: 'surtr',
    rule: '召唤指令仍遵守双主人保护和冲突阵营索敌。',
    deterministicCase: 'Gacha summon command uses Surtr conflict targeting and protects both exact owners',
    eventAssertions: ['指令行动目标不包含两名主人'],
    logAssertions: ['召唤指令写出实际目标'],
  },
  {
    id: 'ST-09',
    subject: 'surtr',
    rule: '黄昏按自身行动机会递增流失，归零后固定八次余命。',
    deterministicCase: 'Twilight drain and eight-opportunity afterglow preserve display, status hits, and original kill credit',
    eventAssertions: ['流失序号连续，余命恰好八次，击杀来源保留'],
    logAssertions: ['每次流失、余命进度和黄昏尽头均有明确日志'],
  },
  {
    id: 'ST-10',
    subject: 'surtr',
    rule: '黄昏余命中的多段技能每段照常命中并触发合法后续。',
    deterministicCase: 'Custom multi-hit skills preserve afterglow hit logs and on-hit effects',
    eventAssertions: ['每段伤害与状态命中索引连续'],
    logAssertions: ['不得把命中写成闪避或提前死亡'],
  },
  {
    id: 'ST-11',
    subject: 'surtr',
    rule: '持续伤害与反击在余命中保留因果来源，不能提前终止余命。',
    deterministicCase: 'Afterglow status and counter damage keep causal logs and original kill credit',
    eventAssertions: ['伤害来源、根事件与最终击杀归属正确'],
    logAssertions: ['余命免死说明紧跟对应伤害'],
  },
  {
    id: 'ST-12',
    subject: 'surtr',
    rule: '余命中的史尔特尔仍可被攻击，但不属于低血处决目标。',
    deterministicCase: 'Afterglow remains attackable without becoming a false low-health or execute target',
    eventAssertions: ['targetable 为真且战术生命比例不触发处决'],
    logAssertions: ['攻击命中与处决判定不自相矛盾'],
  },
  {
    id: 'ST-13',
    subject: 'surtr',
    rule: '史尔特尔每次真实击杀只结算一次，牢鳄与鸮各分得 0.5。',
    deterministicCase: 'Surtr kills split once and Emote preserves fractional nonzero kills',
    eventAssertions: ['一次 defeat 对应一次 0.5/0.5 分账'],
    logAssertions: ['共同击杀分账同时写出两名主人'],
  },
  {
    id: 'ST-14',
    subject: 'surtr',
    rule: '普通控制关系下，混乱和强制目标也不能让史尔特尔攻击两名主人。',
    deterministicCase: 'Confusion and forced targeting can never make Surtr attack either exact owner',
    eventAssertions: ['所有 action_start 目标均排除主人 ID'],
    logAssertions: ['不得出现史尔特尔命中共同主人'],
  },
  {
    id: 'ST-15',
    subject: 'surtr',
    rule: '仅剩史尔特尔及共同主人阵营时，胜负按共同遗产结算且不拖局。',
    deterministicCase: 'Surtr joint legacy resolves as a shared owner victory without stalling',
    eventAssertions: ['比赛结束且获胜阵营包含合法主人'],
    logAssertions: ['结算不得把史尔特尔列为独立冠军'],
  },
  {
    id: 'AU-01',
    subject: 'cross_system',
    rule: '审查器必须识别接管召唤物错误进入拼点。',
    deterministicCase: 'Fault injection detects a controlled summon entering Prophet clash',
    eventAssertions: ['篡改拼点参与者后审查失败'],
    logAssertions: ['报告 controlled-summon-entered-clash'],
  },
  {
    id: 'AU-02',
    subject: 'cross_system',
    rule: '审查器必须识别被接管召唤物选择自身或预言家阵营友军。',
    deterministicCase: 'Fault injection detects illegal controlled-summon targeting',
    eventAssertions: ['篡改 action_start 目标后审查失败'],
    logAssertions: ['报告 controlled-summon-illegal-target'],
  },
  {
    id: 'AU-03',
    subject: 'cross_system',
    rule: '审查器必须识别同一史尔特尔重复发动黄昏。',
    deterministicCase: 'Fault injection detects duplicate Twilight activation',
    eventAssertions: ['重复黄昏状态变化不可通过'],
    logAssertions: ['报告 surtr-twilight-repeated'],
  },
  {
    id: 'AU-04',
    subject: 'cross_system',
    rule: '审查器必须识别非接管状态下史尔特尔攻击共同主人。',
    deterministicCase: 'Fault injection detects Surtr targeting an exact owner',
    eventAssertions: ['篡改目标为主人后审查失败'],
    logAssertions: ['报告 surtr-targeted-exact-owner'],
  },
  {
    id: 'AU-05',
    subject: 'cross_system',
    rule: '审查器必须识别伤害事件的行动者与真实来源不一致。',
    deterministicCase: 'Fault injection detects incorrect damage attribution',
    eventAssertions: ['篡改 actorId 后因果审查失败'],
    logAssertions: ['报告 damage_actor_mismatch'],
  },
  {
    id: 'AU-06',
    subject: 'cross_system',
    rule: '审查器必须识别未复活情况下的重复死亡结算。',
    deterministicCase: 'Fault injection detects duplicate death settlement',
    eventAssertions: ['复制 defeat 后因果审查失败'],
    logAssertions: ['报告 duplicate_defeat_without_revive'],
  },
  {
    id: 'AU-07',
    subject: 'cross_system',
    rule: '预言家接管期间暂停共同主人保护；返还后立即恢复。',
    deterministicCase: 'Ownership audit distinguishes Prophet control from ordinary exact-owner protection',
    eventAssertions: ['接管时间窗内主人可成为目标，时间窗外不可成为目标'],
    logAssertions: ['接管与返还日志定义审查边界'],
  },
];

export function validateYuzuSurtrRuleCatalog(caseNames: readonly string[]): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  const cases = new Set(caseNames);
  YUZU_SURTR_RULE_CATALOG.forEach((entry) => {
    if (ids.has(entry.id)) errors.push(`duplicate rule id ${entry.id}`);
    ids.add(entry.id);
    if (!cases.has(entry.deterministicCase)) {
      errors.push(`${entry.id} references missing deterministic case: ${entry.deterministicCase}`);
    }
    if (entry.eventAssertions.length === 0) errors.push(`${entry.id} has no structured event assertion`);
    if (entry.logAssertions.length === 0) errors.push(`${entry.id} has no log assertion`);
  });
  return errors;
}
